import React,{useEffect, useState} from "react";
import Card from "../../components/Card/Card";
import Nav from "../../components/Nav/Nav";
import Head from "next/head";

const Cats = ()=>{

    const [cats,setCats] = useState([])

    const fetchcats = async ()=>{
        const response = await fetch('/api/cats');
        const data = await response.json();
        setCats(data);
        console.log(data);
    }
    useEffect(()=>{
        fetchcats();
    },[])
    return(
        <>
        <Head>
                <title>Our Cats</title>
                <meta name="description" content="Generated by create next app" />
                
        </Head>
        <Nav/>
        <div className="container mt-5">

            <div style={{display:"flex", flexWrap:"wrap"}}>
            {cats.map((cat) => (
              <Card
                key={cat.id}
                name={cat.name}
                id={cat.id}
                phone={cat.phone}
                email={cat.email}
                image={{ url: cat.image.url, alt: cat.image.alt }}
                isFavourite={cat.favoured}
              />
            ))}
            </div>
            
        </div>
        </>
    );
}
export default Cats;


