import Head from 'next/head'
import Image from 'next/image'
import Jumbotron from '../components/Jumbotron/Jumbotron'
import Nav from '../components/Nav/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cats</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main >
        <Nav/>
        <Jumbotron/>
      </main>

    </div>
  )
}
